### PR TITLE
chore: update dependencies

### PR DESCRIPTION
**Pull request by alexanderleegs**
This PR updates various dependencies to fix vulnerabilities.

- `@aws/sdk` packages
- `dd-trace` - major version bump from 2.30.1 to 4.7.0
- `winston-cloudwatch`
- `serverless`
- `serverless-step-functions`

It also adds an override for `fast-xml-parser` to `^4.2.4` - this was a minor update to the existing dependency used by `is-svg`, which has not been updated.

In addition, `serverless-step-functions-local` has been removed, which was unused and was causing conflicts with `serverless` 3.x versions.

`swc/core`, `swc/helpers`, `swc/cli` have also been removed, as they did not appear to be used.

### CODE REVIEW

**Comment by seaerchin** [comment]
do we actually use 

```
serverless
swc/core and swc/helpers
serverless-step-functions
```

**Comment by alexanderleegs** [comment]
> do we actually use
> 
> ```
> serverless
> swc/core and swc/helpers
> serverless-step-functions
> ```

@kishore03109 mentioned that serverless and serverless-step-functions are still being used, at least until next week. Not sure about swc/core and swc/helpers though

**Comment by kishore03109** [comment]
@alexanderleegs if swe + swe helpers are peer/ dev dep for serverless can remove

**Comment by alexanderleegs** [comment]
> @alexanderleegs if swe + swe helpers are peer/ dev dep for serverless can remove

they're not dev deps for serverless, but we don't really seem to be using them either - have removed those packages from our dev deps

**Review by kishore03109 — APPROVED** [review]
just need to resolve merge conflict ya

**Pull request merged**
