### PR TITLE
Fix: add svg to allowed image types

### PR DESCRIPTION
**Pull request by alexanderleegs**
This PR fixes an issue where svg images were not allowed to be uploaded.

### CODE REVIEW

**Review by harishv7 — DISMISSED** [review]

**Comment by harishv7** [comment]
@alexanderleegs Just to check, is this the first time we are allowing SVGs? If so, have we tried upload and embedding SVGs and if they work fine?

**Comment by alexanderleegs** [comment]
> @alexanderleegs Just to check, is this the first time we are allowing SVGs? If so, have we tried upload and embedding SVGs and if they work fine?

It's really strange - we've allowed svgs for quite a while now, but it seems like editing svgs specifically is buggy - actually let me take a look at the root cause, i think we might not be doing something correctly here

**Comment by kishore03109** [comment]
@alexanderleegs 
> we've allowed svgs for quite a while now, but it seems like editing svgs specifically is buggy - actually let me take a look at the root cause, i think we might not be doing something correctly here

sorry so does this PR fix the issue or is it something like there is a root cause and this is a bandage fix? (if yes, why is this a bandage fix ah?)

**Review by kishore03109 — APPROVED** [review]
am ok with this as a bandage fix, but I am confused about the context around the root cause + what would be the permanent fix. 
Assuming that that will be addressed in a separate pr (correct me if I am wrong here), will just gather the context from there ya

**Comment by alexanderleegs** [comment]
> am ok with this as a bandage fix, but I am confused about the context around the root cause + what would be the permanent fix. Assuming that that will be addressed in a separate pr (correct me if I am wrong here), will just gather the context from there ya

I verified what's the reason behind the different behaviour of create and rename - the reason why creating svgs works currently is that we call `validateAndSanitizeFileUpload`, which has a custom check and handling for svgs - the rename instead only checks against the list of valid file extensions (this is fine because the file content itself does not change), so this fix should work fine

**Pull request merged**
